const AppErrorCode = {
  COMMANDER_NORMAL_EXIT_CODE: "command_normal_exit_code",
  COMMANDER_HELP_DISPLAYED_CODE: "commander_help_displayed_code",
  COMMANDER_UNKNOWN_COMMAND_CODE: "commander_unknown_command_code",
  COMMANDER_UNKNOWN_OPTION_CODE: "commander_unknown_option_code",
  COMMANDER_OPTION_MISSING_ARGUMENT_CODE: "commander_option_missing_argument_code",
  COMMANDER_MISSING_MANDATORY_OPTION_VALUE_CODE: "commander_missing_mandatory_option_value_code",
  COMMANDER_MISSING_ARGUMENT_CODE: "commander_missing_argument_code",
  COMMANDER_EXCESS_ARGUMENTS_CODE: "commander_excess_arguments_code",
  COMMANDER_QUOTED_VALUE_MISSING_CODE: "commander_quoted_value_missing_code",
  COMMANDER_EXCESS_ARGUMENTS_MESSAGE_INVALID_CODE: "commander_excess_arguments_message_invalid_code",
  COMMANDER_CODE_UNSUPPORTED_CODE: "commander_code_unsupported_code",
  UNEXPECTED_ERROR_CODE: "unexpected_error_code",
  PACKAGE_BIN_CONFIG_MISSING_CODE: "package_bin_missing_code",
  PACKAGE_CONFIG_JSON_INVALID_CODE: "package_config_json_invalid_code",
  PACKAGE_CONFIG_SCHEMA_INVALID_CODE: "package_config_schema_invalid_code",
  PACKAGE_CONFIG_NOT_FOUND_CODE: "package_config_not_found_code",
  PLATFORM_NOT_FOUND_CODE: "platform_not_found_code",
  REMOTE_REPOSITORY_PULL_FAILED_CODE: "remote_repository_pull_failed_code",
  REMOTE_SKILL_EMPTY_CODE: "remote_skill_empty_code",
  SKILL_OPTION_INVALID_FORMAT_CODE: "skill_option_invalid_format_code",
  SKILL_NOT_FOUND_CODE: "skill_not_found_code",
  FILE_COPY_FAILED_CODE: "file_copy_failed_code",
  PROMPT_CANCELLED_CODE: "prompt_cancelled_code",
  DIRECTORY_REMOVE_FAILED_CODE: "directory_remove_failed_code",
} as const

export { AppErrorCode }
